config/routes.rb
FindMySpot::Application.routes.draw do

  resources :upvotes
  get "admin/addEvento"
  get "comentarios/del_comentario"
  
  get "comentarios/rating_display"
  
  get "comentarios/downvote"

  get "admin/destroy"

  get "admin/konami"

  get "admin/general"

  get "admin/create"

  get "admin/userPhotos"
  get "admin/user"
  get "admin/userSearch"

  get "admin/venue"

  get "admin/sector"

  get "admin/photo"

  get "admin_controller/venue"

  get "admin_controller/sector"

  get "admin_controller/photos"

   get "recoverpass/recover"
 get "recoverpass/change"
  resources :widgets

  get "profile/show"

  get "profile/index"

  get "sessions/create"

  get "sessions/destroy"

  resources :fotosectors

  resources :fotolugars

  resources :lugars

  resources :bancadas

  resources :sectors

  resources :comentarios

  resources :salas

  resources :estadios

  get "home/show"

  resources :eventos
  resources :eventos, :module => "general"
  resources :recintos

  devise_for :users,  controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  as :user do
    get '/users/sign_up' => 'devise/sessions#new', :as => :new_user_session
    post '/users/sign_in' => 'devise/sessions#create', :as => :user_session
    get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session,
    :via => Devise.mappings[:user].sign_out_via
  end

  resource :home, only: [:show]

  devise_for :users, controllers: { registrations: "users/edit" }

  root :to => 'welcome#index', :as => 'root'

    match '*path' => redirect('/404')

end

app/models/bancada.rb
class Bancada < ActiveRecord::Base
  attr_accessible :nome
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  attr_accessible :corpo, :user_id, :sector_id, :user_id, :fotosector_id, :fotopath
  belongs_to :user
  belongs_to :fotosector
  belongs_to :sector
end

app/models/estadio.rb
class Estadio < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :date, :description, :title, :promotor, :url, :recinto_id
  belongs_to :recinto
end

app/models/fotolugar.rb
class Fotolugar < ActiveRecord::Base
  attr_accessible :descricao, :foto, :sector_id, :user_ids
  belongs_to :user
  belongs_to :sector
end

app/models/fotosector.rb
class Fotosector < ActiveRecord::Base
  attr_accessible :foto, :sector_id, :nmr_checkins, :nmr_ratings, :rating
  belongs_to :sector
  has_many :comentario
  has_many :upvotes
  has_and_belongs_to_many :users
end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
  attr_accessible :descritivo
end

app/models/recinto.rb
class Recinto < ActiveRecord::Base
  attr_accessible :capacidade, :morada, :nome, :notas, :telefone
  has_many :eventos
  has_many :sectors
end

app/models/sala.rb
class Sala < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  attr_accessible :descritivo, :distancia_bar, :distancia_wc, :recinto_id
  belongs_to :recinto
  has_many :fotosector
  has_many :comentarios
  has_many :fotolugars
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  attr_accessible :fotosector_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable,:validatable, :trackable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :photo, :banned

  has_many :comentario
  has_many :fotolugar
  has_and_belongs_to_many :fotosectors

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data["name"],
    #        email: data["email"],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    user
  end
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/fotolugars_controller.rb
class FotolugarsController < ApplicationController
  before_filter :set_fotolugar, only: [:show, :edit, :update, :destroy]

  def index
    @fotolugars = Fotolugar.all
    respond_with(@fotolugars)
  end

  def show
    respond_with(@fotolugar)
  end

  def new
    @fotolugar = Fotolugar.new
    respond_with(@fotolugar)
  end

  def edit
  end

  def create
    @fotolugar = Fotolugar.new(params[:fotolugar])
    @fotolugar.save
    respond_with(@fotolugar)
  end

  def update
    @fotolugar.update_attributes(params[:fotolugar])
    respond_with(@fotolugar)
  end

  def destroy
    @fotolugar.destroy
    respond_with(@fotolugar)
  end

  private
    def set_fotolugar
      @fotolugar = Fotolugar.find(params[:id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/fotolugars_helper.rb
module FotolugarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/fotolugars/_form.html.erb
<%= form_for(@fotolugar) do |f| %>
  <% if @fotolugar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fotolugar.errors.count, "error") %> prohibited this fotolugar from being saved:</h2>

      <ul>
      <% @fotolugar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foto %><br />
    <%= f.text_area :foto %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotolugars/edit.html.erb
<h1>Editing fotolugar</h1>

<%= render 'form' %>

<%= link_to 'Show', @fotolugar %> |
<%= link_to 'Back', fotolugars_path %>

app/views/fotolugars/index.html.erb
<h1>Listing fotolugars</h1>

<table>
  <tr>
    <th>Foto</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fotolugars.each do |fotolugar| %>
  <tr>
    <td><%= fotolugar.foto %></td>
    <td><%= fotolugar.descricao %></td>
    <td><%= link_to 'Show', fotolugar %></td>
    <td><%= link_to 'Edit', edit_fotolugar_path(fotolugar) %></td>
    <td><%= link_to 'Destroy', fotolugar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fotolugar', new_fotolugar_path %>

app/views/fotolugars/new.html.erb
<h1>New fotolugar</h1>

<%= render 'form' %>

<%= link_to 'Back', fotolugars_path %>

app/views/fotolugars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Foto:</b>
  <%= @fotolugar.foto %>
</p>

<p>
  <b>Descricao:</b>
  <%= @fotolugar.descricao %>
</p>


<%= link_to 'Edit', edit_fotolugar_path(@fotolugar) %> |
<%= link_to 'Back', fotolugars_path %>